#!/bin/bash

LOCATION="/blacklist_checker" # Directory location (do not include trailing /)
EMAIL="" # Email address to send reports to (leave empty to disable mailing function)
FROM="" # Email address to send reports from
SUBJECT="IPv4 Blacklist Report" # Email subject
SUCCESS="" # Set to true to get a success email saying no IPs are blacklisted
METHOD="msmtp" # Method to send email msmtp or mail
ssub=10s # Sleep between subnets, default of "10s" should be fine
sip=1s # Sleep between each IP address, default of "1s" should be fine
sblck=0.1s # Sleep between each blacklist check, default of "0.1s" should be fine

if [ ! -z "$LOCATION" ]; then
    while read i;
    do
        i1=`echo $i | awk '{print $1}'`
        i2=`echo $i | awk '{print $2}'`
        i3=`echo $i | awk '{print $3}'`
        while [[ $i2 -le $i3 ]]
        do
            ip=`echo $i1.$i2 |awk -F"." '{for(i=NF;i>0;i--) printf i!=1?$i".":"%s",$i}'`
            for l in $(cat $LOCATION/list)
            do
                res=`dig +short $ip.$l | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep 127.0.*`
                if [ ! -z "$res" ]; then
                    EMAILMESSAGE=`echo "ip $i1.$i2 blacklisted on $l list - gotten result $res"`
                    if [ ! -z "$EMAIL"  ]; then #do not send email if dont want it
                        echo $EMAILMESSAGE >> $LOCATION/blacklist.txt
                    fi
                    echo $EMAILMESSAGE
                else
                    echo "ip $i1.$i2 not blacklisted on $l list - gotten result $res"
                fi
                sleep $sblck
            done
            ((i2 = i2 + 1))
            sleep $sip
        done
        sleep $ssub
    done <$LOCATION/sub

    if [ -f $LOCATION/blacklist.txt ]; then
        printf "To: $EMAIL\r\nFrom: Blacklist Checker <$FROM>\r\nDate: $(date)\r\nSubject: $SUBJECT\r\n\r\nBLChecker has indicated the below IPs are on the associated blacklists:\r\n\r\n" > $LOCATION/temp.txt
        cat $LOCATION/temp.txt $LOCATION/blacklist.txt >> $LOCATION/mail.txt
        printf "\r\nYour friendly blacklist checking bot" >> $LOCATION/mail.txt
        rm $LOCATION/temp.txt $LOCATION/blacklist.txt
        if [ $METHOD = "mail" ]; then
            cat $LOCATION/mail.txt | mail -s "$SUBJECT" $EMAIL
        else
            cat $LOCATION/mail.txt | msmtp $EMAIL
        fi
        printf "$SUBJECT was sent successfully.\r\n"
        rm $LOCATION/mail.txt
    else
        if [ ! -z "$SUCCESS" ]; then
            printf "LOG: no ip's blacklisted\r\n"
            printf "To: $EMAIL\r\nFrom: Blacklist Checker <$FROM>\r\nDate: $(date)\r\nSubject: $SUBJECT\r\n\r\nBLChecker has indicated there are no IPs listed in any blacklists checked.\r\n\r\nYour friendly blacklist checking bot" >> $LOCATION/mail.txt
            if [ $METHOD = "mail" ]; then
                cat $LOCATION/mail.txt | mail -s "$SUBJECT" $EMAIL
            else
                cat $LOCATION/mail.txt | msmtp $EMAIL
            fi
            printf "$SUBJECT was sent successfully.\r\n"
            rm $LOCATION/mail.txt
        else
            printf "LOG: no ip's blacklisted or mailing disabled.\r\n"
        fi
    fi
else
    printf "ATTENTION: You must set the LOCATION variable.\r\n"
fi